# Generated by Django 5.2.10 on 2026-01-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_podcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
